language: python
python:
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- pip install pipenv
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
install:
- pipenv install --dev
script:
- pipenv run flake8
- pipenv run py.test
after_script:
- ./cc-test-reporter after-build --exit-code ${TRAVIS_TEST_RESULT}
deploy:
- provider: pypi
  user: amancevice
  password:
    secure: >-
      OR+02EZH+cEGjftj8yc2sE8zfbJj9BaOBiCsn9FEjZoFb3naGTqm/l+mYZERIMBtKt7bv5R+6
      3+7aSlQ3UZcDgwp9JZzz+Jag25VbANNxCGyjWc4Ff5VxNLc06PnglZf9IFUuiM3OFx0gHT3Eo
      5X0DHN3zCucvofha/uK02yYJwj3zwU7u/QsP+gi0p6Sf+SxBaGM1OuDL1yhnE8qtB92zA1OQX
      h10wLYYkHbNk0q6DQPn7+7STziH1HzQ0TEexIFt3eaJIUlvi9/TWx+66+pi4OWqKQVCzHeGwh
      T6JirsNmoSutC7spBWq09RK2+oNyvL+X0KAvsJO7KZrXZdFNJCDWH+MrOC4Uy8NJBv9CHhFLp
      WufurFGFrYt4k+dwDyE64uShex+NE8nggPdgVYy8BNpX5QekebJSR9OeBUxa4aJpL7Z/MJ5id
      Pi+Vqsrp92Ja8PMiqzgOfwTxUTrUki1Ja00smsx68rzBKTwVhMm64vXf2VA1HbP5cFdx7cpMO
      scrM0Q+/oKhPFdgNGvqlP+n6lySRNjn5YbxfoHSj1zYGtlhantYwlR7CopQZRMMj74NaZe2zn
      +DMCF18AbviRAzv4eKcRddZz8Ry7ZHb8knzxBR6lZhdeDHK58czIFJcaXiZypC49fBDvxp9ab
      cX3njxLXV9TkTfh/XUKhkF3VaM=
  on:
    repo: amancevice/redpanda
    tags: true
