version: '2'
services:
  python2:
    build: examples/python27
    working_dir: /redpanda/examples/python27
    ports:
      - "2700:2700"
    volumes:
      - ".:/redpanda"
  python3:
    build: examples/python35
    working_dir: /redpanda/examples/python35
    ports:
      - "3500:3500"
    volumes:
      - ".:/redpanda"
