name: pytest
on:
  pull_request:
  push:
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        sqlalchemy:
          - ">= 1.4"
          - ">= 1.3, < 1.4"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: amancevice/setup-code-climate@v1
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - run: cc-test-reporter before-build
      - run: |
          pip install pipenv
          pipenv install --dev
          pipenv run pip install 'sqlalchemy ${{ matrix.sqlalchemy }}'
      - run: make
      - run: cc-test-reporter after-build
        if: ${{ github.event_name != 'pull_request' }}
